# Generated by Django 4.2.6 on 2024-01-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bungu', '0004_post_thumbnail_alter_post_date_alter_post_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
